version: "3.9"

services:
  backend:
    build: ./rms-backend
    container_name: rental-backend
    restart: unless-stopped
    environment:
      PORT: 4000
      DATABASE_URL: "mysql://root:examplepassword@mysql:3306/rms_db"
      JWT_SECRET: "change_me"
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    networks:
      - rental-net

  frontend:
    build: ./rms-frontend
    container_name: rental-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rental-net

  mysql:
    image: mysql:8
    container_name: rental-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: rms_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rental-net

  adminer:
    image: adminer
    container_name: rental-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - rental-net

networks:
  rental-net:

volumes:
  mysql_data:
